mvc/tutorials/mvc-with-entity-framework/sample/src/ContosoBooks/Models/Author.cs
using System.ComponentModel.DataAnnotations;

namespace ContosoBooks.Models
{
    public class Author
    {
        public int AuthorID { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "First Name")]
        public string FirstMidName { get; set; }
    }
}

mvc/tutorials/mvc-with-entity-framework/sample/src/ContosoBooks/Controllers/AuthorController.cs
using ContosoBooks.Models;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Storage;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoBooks.Controllers
{
    public class AuthorController : Controller
    {
        [FromServices]
        public BookContext BookContext { get; set; }

        public IActionResult Index()
        {
            return View(BookContext.Authors);
        }

        public async Task<ActionResult> Details(int id)
        {
            Author author = await BookContext.Authors
                .SingleOrDefaultAsync(a => a.AuthorID == id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("LastName", "FirstMidName")] Author author)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    BookContext.Authors.Add(author);
                    await BookContext.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            catch (DataStoreException)
            {
                ModelState.AddModelError(string.Empty, "Unable to save changes.");
            }

            return View(author);
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<ActionResult> ConfirmDelete(int id, bool? retry)
        {
            Author author = await FindAuthorAsync(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            ViewBag.Retry = retry ?? false;
            return View(author);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                Author author = await FindAuthorAsync(id);
                BookContext.Authors.Remove(author);
                await BookContext.SaveChangesAsync();
            }
            catch (DataStoreException)
            {
                return RedirectToAction("Delete", new { id = id, retry = true });
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            Author author = await FindAuthorAsync(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(int id, [Bind("LastName", "FirstMidName")] Author author)
        {
            try
            {
                author.AuthorID= id;
                BookContext.Authors.Attach(author);
                BookContext.Entry(author).State = EntityState.Modified;
                await BookContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (DataStoreException)
            {
                ModelState.AddModelError(string.Empty, "Unable to save changes.");
            }
            return View(author);
        }

        private Task<Author> FindAuthorAsync(int id)
        {
            return BookContext.Authors.SingleOrDefaultAsync(author => author.AuthorID == id);
        }
    }
}

mvc/tutorials/mvc-with-entity-framework/sample/src/ContosoBooks/Views/Author/Create.cshtml
@model ContosoBooks.Models.Author

<div>
  <form asp-controller="Author" asp-action="Create" method="post">
    <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
    <div class="form-group">
      <label asp-for="LastName"></label>
      <input asp-for="LastName" class="form-control"/>
      <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
      <label asp-for="FirstMidName"></label>
      <input asp-for="FirstMidName" class="form-control" />
      <span asp-validation-for="FirstMidName" class="text-danger"></span>
    </div>
    <input type="submit" class="btn btn-default" value="Create" />
  </form>
</div>

@section Scripts {
    <script src="~/lib/jquery-validation/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

mvc/tutorials/mvc-with-entity-framework/sample/src/ContosoBooks/Views/Author/Delete.cshtml
@model ContosoBooks.Models.Author

@{
    ViewBag.Title = "Confirm Delete";
}

<h3>Are you sure you want to delete this?</h3>

@if (ViewBag.Retry)
{
    <p class="alert-danger">Error deleting. Retry?</p>
}

<div>
  <dl class="dl-horizontal">
    <dt>
      @Html.DisplayNameFor(model => model.LastName)
    </dt>
    <dd>
      @Html.DisplayFor(model => model.LastName)
    </dd>

    <dt>
      @Html.DisplayNameFor(model => model.FirstMidName)
    </dt>
    <dd>
      @Html.DisplayFor(model => model.FirstMidName)
    </dd>
  </dl>

  <div>
    <form asp-controller="Author" asp-action="Delete" method="post">
      <div class="form-group">
        <input type="submit" class="btn btn-default" value="Delete" />
      </div>
    </form>

    <p><a asp-controller="Author" asp-action="Index">Back to List</a></p>
  </div>
</div>

mvc/tutorials/mvc-with-entity-framework/sample/src/ContosoBooks/Views/Author/Details.cshtml
﻿@model ContosoBooks.Models.Author

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<div>
  <dl class="dl-horizontal">
    <dt>
      @Html.DisplayNameFor(model => model.LastName)
    </dt>
    <dd>
      @Html.DisplayFor(model => model.LastName)
    </dd>

    <dt>
      @Html.DisplayNameFor(model => model.FirstMidName)
    </dt>
    <dd>
      @Html.DisplayFor(model => model.FirstMidName)
    </dd>
  </dl>
</div>
<p>
  <a asp-action="Edit" asp-route-id="@Model.AuthorID">Edit</a> |
  <a asp-action="Index">Back to List</a>
</p> 

mvc/tutorials/mvc-with-entity-framework/sample/src/ContosoBooks/Views/Author/Edit.cshtml
@model ContosoBooks.Models.Author

<div>
  <form asp-controller="Author" asp-action="Update" method="post" asp-route-id="@Model.AuthorID">
    <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
    <div class="form-group">
      <label asp-for="LastName"></label>
      <input asp-for="LastName" class="form-control"/>
      <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
      <label asp-for="FirstMidName"></label>
      <input asp-for="FirstMidName" class="form-control" />
      <span asp-validation-for="FirstMidName" class="text-danger"></span>
    </div>
    <input type="submit" class="btn btn-default" value="Save" />
  </form>
</div>

@section Scripts {
  <script src="~/lib/jquery-validation/jquery.validate.js"></script>
  <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

mvc/tutorials/mvc-with-entity-framework/sample/src/ContosoBooks/Views/Author/Index.cshtml
@model IEnumerable<ContosoBooks.Models.Author>
@{
    ViewBag.Title = "Authors";
}
<p>
    <a asp-action="Create">Create New Author</a>
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstMidName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstMidName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.AuthorID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.AuthorID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.AuthorID">Delete</a>
            </td>
        </tr>
    }

</table>